import {build} from 'esbuild';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const codexLauncher = JSON.parse(await readFile(new URL('../plugins/remctl/mcp.json',import.meta.url),'utf8')).mcpServers.remctl;
const claudeLauncher = JSON.parse(await readFile(new URL('../plugins/claude-code/.mcp.json',import.meta.url),'utf8')).mcpServers.remctl;
assert.match(codexLauncher.env.REMCTL_PLUGIN_BUILD,/^[a-f0-9]{16}$/);
assert.equal(claudeLauncher.env.REMCTL_PLUGIN_BUILD,codexLauncher.env.REMCTL_PLUGIN_BUILD,'Both plugins must load the same build');
assert.equal(codexLauncher.env.REMCTL_PLUGIN,'1');
assert.equal(claudeLauncher.env.REMCTL_PLUGIN,undefined,'Claude Code uses shared tools without the Codex workspace metadata');
const bundle=await build({entryPoints:[new URL('./src/reminder-helpers.ts',import.meta.url).pathname],bundle:true,write:false,format:'esm',platform:'node'});
const {arrangeReminders,selectionRange,rescheduledDue,recurrenceText,isReminder,notePresentation,todaySection,systemListVisible,pinnedSidebarLists,sidebarLists,sidebarKey,sidebarScope,orderSidebarItems,moveSidebarItem}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
assert.equal(isReminder({id:9,title:'Groceries',isGroceries:true}),false);
assert.equal(isReminder({status:'ok',id:9}),false);
assert.equal(isReminder({id:9,title:'Milk',completed:false}),true);
const items=[{id:3,parentID:1,title:'child'},{id:2,title:'other'},{id:1,section:'Design',title:'parent'},{id:4,parentID:3,title:'grandchild'}];
assert.deepEqual(arrangeReminders(items).map(i=>[i.id,i.depth,i.groupSection]),[[2,0,undefined],[1,0,'Design'],[3,1,'Design'],[4,2,'Design']]);
assert.deepEqual(arrangeReminders(items,[1]).map(i=>i.id),[2,1]);
assert.deepEqual(arrangeReminders(items.filter(i=>i.id!==1)).map(i=>i.id),[3,4,2]);
assert.equal(arrangeReminders([{id:1,parentID:2},{id:2,parentID:1}]).length,2);
assert.deepEqual(selectionRange(arrangeReminders(items),1,4),[1,3,4]);
assert.deepEqual(selectionRange(items,null,2),[2]);
assert.equal(rescheduledDue({dueDate:'2026-09-30T14:30:00',allDay:false},'2026-10-02'),'2026-10-02 14:30');
assert.equal(rescheduledDue({dueDate:'2026-09-30T00:00:00',allDay:true},'2026-10-02'),'2026-10-02');
assert.equal(recurrenceText({frequency:'weekly',interval:2,daysOfWeek:[2,6]}),'weekly x2 mon,fri');
const ordinal={frequency:'monthly',interval:2,daysOfWeekDetailed:[{dayOfTheWeek:6,weekNumber:-1}],count:8};
assert.deepEqual(JSON.parse(recurrenceText(ordinal)),ordinal);
assert.deepEqual(notePresentation(JSON.stringify({changelog:'One\\nTwo',labels:'App Update',version:'5.0',app_url:'https://example.com'})), {text:'One\nTwo',label:'App Update',version:'5.0'});
assert.equal(notePresentation('{unusual note}').text,'{unusual note}');
assert.equal(todaySection({dueDate:'2026-09-30T14:00:00',allDay:false},'2026-09-30'),'Afternoon');
assert.equal(todaySection({dueDate:'2026-09-30T00:00:00',allDay:true},'2026-09-30'),'Today');
assert.equal(todaySection({dueDate:'2026-09-29T18:00:00',allDay:false},'2026-09-30'),'Overdue');
const nativeSmart = [{kind:'built-in',smartListType:'com.apple.reminders.smartlist.today'}, {kind:'built-in',smartListType:'com.apple.reminders.smartlist.flagged',pinnedDate:-63114076800,pinned:false}, {kind:'built-in',smartListType:'com.apple.reminders.smartlist.completed',pinned:true,pinnedDate:20}];
assert.equal(systemListVisible(nativeSmart,'today'),true);
assert.equal(systemListVisible(nativeSmart,'scheduled'),true);
assert.equal(systemListVisible(nativeSmart,'flagged'),false);
assert.equal(systemListVisible(nativeSmart,'completed'),true);
const pins = pinnedSidebarLists([{id:3,pinned:true,pinnedDate:30,parentListId:8},{id:1,pinned:true,pinnedDate:10},{id:8,isGroup:true,pinned:true},{id:4,pinned:false}], [{id:7,kind:'custom',pinned:true,pinnedDate:20},...nativeSmart]);
assert.deepEqual(pins.map(list=>[list.id,list.sidebarKind]),[[1,'list'],[7,'smart'],[3,'list']]);
const folders = [{id:8,title:'Priorities',isGroup:true},{id:3,title:'Errands',parentListId:8},{id:4,title:'Pinned',pinned:true}];
const smartFolders = [{id:10,name:'This Week',kind:'custom',parentListId:8}, {id:11,name:'Ungrouped',kind:'custom'}, {id:12,name:'Missing folder',kind:'custom',parentListId:99}, {id:13,name:'Pinned smart',kind:'custom',pinned:true}, ...nativeSmart];
const sidebar = sidebarLists(folders, smartFolders);
assert.deepEqual(sidebar.filter(list=>list.parentListId === 8).map(list=>[list.title,list.sidebarKind]), [['Errands','list'],['This Week','smart']]);
assert.deepEqual(sidebar.filter(list=>!list.parentListId).map(list=>list.title), ['Priorities','Ungrouped','Missing folder']);
const manual = [{id:1,title:'Home',objectUUID:'HOME'}, {id:2,title:'Miscellaneous',isGroup:true,objectUUID:'MISC'}, {id:3,title:'Priorities',isGroup:true,objectUUID:'PRIORITIES'}, {id:4,title:'Work',objectUUID:'WORK'}];
const workFirst = moveSidebarItem(manual, 'list:WORK', -1);
assert.deepEqual(orderSidebarItems(manual, workFirst).map(list=>list.title), ['Home','Miscellaneous','Work','Priorities']);
assert.deepEqual(orderSidebarItems(manual, ['list:HOME','list:WORK','list:PRIORITIES','list:MISC']).map(list=>list.title), ['Home','Work','Priorities','Miscellaneous']);
assert.equal(sidebarScope({id:10,kind:'custom',parentListId:3},manual), 'group:PRIORITIES');
assert.equal(sidebarScope({id:10,kind:'custom',parentListId:3,pinned:true},manual), 'pinned');
assert.equal(sidebarScope({id:10,parentListId:99},manual), 'top');
assert.equal(sidebarKey({id:4,kind:'custom',objectUUID:'WORK'}), 'smart:WORK');
assert.deepEqual(moveSidebarItem(manual,'list:HOME',-1),manual.map(sidebarKey));
assert.deepEqual(orderSidebarItems([{id:55,title:'Work',objectUUID:'WORK'},manual[0],{id:6,title:'New',objectUUID:'NEW'}], ['list:REMOVED','list:HOME','list:WORK']).map(list=>list.title), ['Home','Work','New']);
assert.deepEqual(orderSidebarItems(manual, []).map(list=>list.title), manual.map(list=>list.title));
console.log('Interaction contracts passed: hierarchy, collapse, range selection, calendar time preservation, recurrence fidelity.');
const {execFileSync}=await import('node:child_process');
const {OpenAIFormSchema,OpenAISettingsReadResultSchema,OpenAIUiToolMetadataSchema}=await import('@openai/mcp-extensions/server');
const contract=JSON.parse(execFileSync('python3',[new URL('../tests/export_desktop_contract.py',import.meta.url).pathname],{encoding:'utf8'}));
OpenAIFormSchema.parse(contract.form);
OpenAISettingsReadResultSchema.parse(contract.settings);
for(const tool of contract.tools) if(tool._meta?.['openai/ui']) OpenAIUiToolMetadataSchema.parse(tool._meta['openai/ui']);
console.log('OpenAI SDK contract validation passed: native rich forms, settings, and app entrypoints.');
const quickCaptureBundle = await build({entryPoints:[new URL('./src/quick-capture.ts',import.meta.url).pathname],bundle:true,write:false,format:'esm',platform:'node'});
const {saveCapture} = await import('data:text/javascript;base64,'+Buffer.from(quickCaptureBundle.outputFiles[0].text).toString('base64'));
let created = 0, attached = 0, checkpoints = [];
const captureResult = await saveCapture({operationId:'capture-op', images:[{id:'image-1', name:'shot.png', mimeType:'image/png', data:'c2hvdA=='}]}, {
  create: async () => { created++; return {status:'created', id: 77}; },
  attach: async () => { attached++; return {status:'ok'}; },
  checkpoint: state => checkpoints.push(JSON.parse(JSON.stringify(state))),
});
assert.equal(created, 1);
assert.equal(attached, 1);
assert.equal(captureResult.reminderId, 77);
assert.equal(captureResult.images[0].attached, true);
assert.equal(checkpoints.length, 2);
let uncertain = false;
try { await saveCapture({operationId:'uncertain-op', images:[]}, {create: async () => {throw new Error('timeout');}, attach: async () => ({}), checkpoint: state => {uncertain = Boolean(state.blocked);}}); } catch {}
assert.equal(uncertain, true);
console.log('Quick capture contract passed: create once, attach once, checkpoint uncertain writes.');
